######################## default configuration ####################
baseURL = ""
title = "FSJP"
# Faculté des Sciences Juridiques et Politiquess
theme = "educenter-hugo-master"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "fsjp-uy2-Soa" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################## navigation ###############################



# main menu
[[menu.main]]
weight = 1
name = "La Faculté"
hasChildren = true

  [[menu.main]]
  parent = "La Faculté"
  name = "A propos de la Faculté"
  URL = "about"
  weight = 11

  [[menu.main]]
  parent = "La Faculté"
  name = "Le Mot du Doyen"
  URL = "notice"
  weight = 12

  [[menu.main]]
  parent = "La Faculté"
  name = "Historique"
  URL = "teacher"
  weight = 13

  [[menu.main]]
  parent = "La Faculté"
  name = "Organigramme"
  URL = "event"
  weight = 14

  [[menu.main]]
  parent = "La Faculté"
  name = "Les Campus"
  URL = "scholarship"
  weight = 15

[[menu.main]]
name = "Les Formations"
URL = "course"
weight = 2
hasChildren = true

  [[menu.main]]
  parent = "Les Formations"
  name = "Calendrier Universitaire"
  URL = "notice"
  weight = 20

  [[menu.main]]
  parent = "Les Formations"
  name = "Licence"
  URL = "scholarship"
  weight = 21

  [[menu.main]]
  parent = "Les Formations"
  name = "Master"
  URL = "scholarship"
  weight = 22

  [[menu.main]]
  parent = "Les Formations"
  name = "Doctorat"
  URL = "scholarship"
  weight = 23


[[menu.main]]
name = "La recherche"
URL = "research"
weight = 3

[[menu.main]]
name = "Actualités"
URL = "blog"
weight = 4
  
[[menu.main]]
name = "Espace Etudiant"
URL = "course"
weight = 5
hasChildren = true

  [[menu.main]]
  parent = "Espace Etudiant"
  name = "Inscription"
  URL = "scholarship"
  weight = 51

  [[menu.main]]
  parent = "Espace Etudiant"
  name = "Documents Utiles"
  URL = "Documents"
  weight = 52


[[menu.main]]
name = "Contact"
URL = "contact"
weight = 6

# footer menu

[[menu.footer]]
name = "teacher"
URL = "teacher"

[[menu.footer]]
name = "notice"
URL = "notice"

[[menu.footer]]
name = "event"
URL = "event"

[[menu.footer]]
name = "scholarship"
URL = "scholarship"

[[menu.footer]]
name = "research"
URL = "research"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Site de la FSJP Uy2 Soa Cameroun"
author = "MTA"
# contact info
address = "Soa Cameroun"
mobile = "+237673656703"
email = "fsjp@univ-yaounde2.org"
# contact form action
contact_form_action = "mailto:tobie.manga@univ-yaounde2.org" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
#mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
#mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
# [params.map]
# enable = true
# gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
# map_latitude = "51.5223477"
# map_longitude = "-0.1622023"
# map_marker = "images/marker.png" # marker size 37*55 px
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

#[[params.social]]
#title = "instagram"
#icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "github"
#icon = "ti-github" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 FSJP-Uy2 Soa"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 1
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2020 FSJP-Uy2 Soa"